Caplit unmarshal
devsisters/go-capnproto pull request #1
Opened 2019-07-02 10:41 UTC by bbashong

https://github.com/devsisters/gb-server-game/pull/954

2019-07-12 06:02 UTC, WKBae requested changes
이 레포를 계속 public으로 둘 지, 아예 우리걸로 만들지 고민해봐야 할 것 같아요.

2019-07-12 06:02 UTC, WKBae commented on go.mod
> +	github.com/glycerine/go-capnproto v0.0.0-20190118050403-2d07de3aa7fc
import를 glycerine/ 대신 devsisters/ 로 하면 glycerine/go-capnproto 패키지를 참조할 필요도 없어지지 않나요?

2019-07-12 06:02 UTC, WKBae commented on capnpc-go/struct.go
> +				if t.Which == {{.structName}}_{{.name}} {
이걸 switch-case로 하면 어떨까요? enum 갯수가 많아지면 생성되는 코드와 비교 횟수가 그만큼 많아지는 것 같아서요

2019-07-12 06:02 UTC, WKBae commented on caplitparser/lex.go
> +	lexer := &lexer{}
사소한건데, `lexer{}`가 아니라 `&lexer{}`로 한 이유가 있나요?

2019-07-12 06:02 UTC, WKBae commented on capnpc-go/struct.go
> +			func (s *{{.name}}_Struct) Copy() *{{.name}}_Struct {
Copy? Clone?
그리고 s를 포인터가 아니라 value 리시버로 받아서 nested object만 recursive하게 복사해도 되지 않을까요?
아니면 첫 줄에 `if s == nil { return nil }`이 있으면 여러 로직이 단순해질 수 있을 것 같아요

2019-07-12 06:02 UTC, WKBae commented on capnpc-go/struct.go
> +			};
세미콜론!
여기 말고도 여러 군데에 들어가있던데, 빌드하는 데 필요해서 넣은건가요?

2019-07-12 06:02 UTC, WKBae commented on capnpc-go/struct.go
> +			panic("List of List not supported now")
TODO 같은거 달아두고 노션같은데에 기록해두는게 좋을 것 같아요
당장 같은 레포에 있는 예시도 이거에 걸려서 테스트를 한다면 깨질 수 있는 부분이 걸려서요

2019-07-12 06:02 UTC, WKBae commented on capnpc-go/caplit_marshal.go
> +	switch n.Which() {
default는 안넣어도 괜찮을까요?

2019-07-17 06:19 UTC, cinakyn reviewed
전 private으로 전환하고싶어요

2019-07-17 06:19 UTC, cinakyn commented on go.mod
> +	github.com/glycerine/go-capnproto v0.0.0-20190118050403-2d07de3aa7fc
저희가 이미 있는 프로젝트를 Forking한거라서 이미 내부 소스코드에 glycerine을 import하고있어요.
모든 glycerine을 devsisters로 replace 해야 해서 이렇게 바꿨습니다.
만약 이게 진짜 forking이었고 위 방법대로 했다면 merge할때 아주 힘들거에요.

2019-07-17 06:19 UTC, bbashong commented on caplitparser/lex.go
> +	lexer := &lexer{}
Parse function 호출 할 때 포인터로 넘겨야해서요. 
불필요하게 heap을 할당할 순 있는데, 일단 서비스 코드가 아니기 때문에 (generation 코드임) compiler를 믿고 그냥 두려고 합니다.

2019-07-17 06:19 UTC, bbashong commented on capnpc-go/caplit_marshal.go
> +	switch n.Which() {
이건 제가 짠 코드가 아니에용

2019-07-17 06:19 UTC, bbashong commented on capnpc-go/caplit_marshal.go
> +	switch n.Which() {
file name modification입니다.

2019-07-17 06:19 UTC, bbashong commented on capnpc-go/struct.go
> +			};
literal string을 코드안에 예쁘게 적으려다보니 애매하게 또는 의도치않게 줄바꿈이 들어가는경우가 있어서, 세미콜론으로 명시적으로 넣어야 할필요가 있었어요. 지금 다 짠 상태여서 한번 세미콜론 안넣고 로직짤수있는지 한번 볼게요

2019-07-17 06:19 UTC, bbashong commented on capnpc-go/struct.go
> +			panic("List of List not supported now")
미래에도 진행하지 않을 기능이라 TODO는 필요 없을 것 같아요. List of List가 구현이 안됐다는 내용은 panic 메세지로 충분히 전달 될  것 같습니다.

2019-07-17 06:19 UTC, bbashong commented on capnpc-go/struct.go
> +				if t.Which == {{.structName}}_{{.name}} {
원본코드 쪽 컨벤션 따라가다보니까 그렇게 됐습니다.

2019-07-17 06:54 UTC, bbashong commented on caplitparser/lex.go
> +	lexer := &lexer{}
간단한건데 그냥 수정할게요

2019-07-17 11:38 UTC, bbashong commented on capnpc-go/struct.go
> +			};
시도해봤는데, code안에 code를 다시 template하는 경우 문제가 되네요. 줄바꿈이 있는지 없는지 명시적으로 적어주는게 나아보입니다.

2019-07-22 08:40 UTC, merged